# Generated by Django 3.0.7 on 2020-06-27 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='название фильма')),
                ('gener', models.CharField(max_length=25, verbose_name='жанр фильма')),
                ('country', models.CharField(max_length=25, verbose_name='страна фильма')),
                ('image', models.ImageField(blank=True, upload_to='film_image')),
                ('year', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='год производства')),
                ('short_desc', models.CharField(blank=True, max_length=129, verbose_name='краткое описание фильма')),
                ('description', models.TextField(blank=True, verbose_name='описание фильма')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='стоимость просмотра')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category')),
            ],
        ),
    ]
