# Generated by Django 3.0.7 on 2020-06-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='category',
        ),
        migrations.RemoveField(
            model_name='film',
            name='country',
        ),
        migrations.RemoveField(
            model_name='film',
            name='gener',
        ),
        migrations.RemoveField(
            model_name='film',
            name='image',
        ),
        migrations.RemoveField(
            model_name='film',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='film',
            name='price',
        ),
        migrations.RemoveField(
            model_name='film',
            name='short_desc',
        ),
        migrations.RemoveField(
            model_name='film',
            name='year',
        ),
        migrations.AddField(
            model_name='film',
            name='link_to_trailer',
            field=models.CharField(blank=True, max_length=200, verbose_name='краткое описание фильма'),
        ),
        migrations.AddField(
            model_name='film',
            name='main_picture',
            field=models.ImageField(blank=True, upload_to='main_picture'),
        ),
        migrations.AddField(
            model_name='film',
            name='picture_gallery',
            field=models.ImageField(blank=True, upload_to='picture_gallery'),
        ),
        migrations.AddField(
            model_name='film',
            name='seo_Keywords',
            field=models.CharField(blank=True, max_length=129, verbose_name='seo Keywords'),
        ),
        migrations.AddField(
            model_name='film',
            name='seo_description',
            field=models.TextField(blank=True, verbose_name='seo description'),
        ),
        migrations.AddField(
            model_name='film',
            name='seo_title',
            field=models.CharField(blank=True, max_length=129, verbose_name='seo title'),
        ),
        migrations.AddField(
            model_name='film',
            name='seo_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='seo url'),
        ),
        migrations.AddField(
            model_name='film',
            name='type_film_2d',
            field=models.BooleanField(default=False, verbose_name='2d'),
        ),
        migrations.AddField(
            model_name='film',
            name='type_film_3d',
            field=models.BooleanField(default=False, verbose_name='3d'),
        ),
        migrations.AddField(
            model_name='film',
            name='type_film_imax',
            field=models.BooleanField(default=False, verbose_name='imax'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
