# Generated by Django 3.0.7 on 2020-06-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200627_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='film',
            name='main_picture',
            field=models.ImageField(blank=True, upload_to='Главная картинка', verbose_name='название ***'),
        ),
        migrations.AlterField(
            model_name='film',
            name='picture_gallery',
            field=models.ImageField(blank=True, upload_to='Галерея картинок'),
        ),
    ]
