# Generated by Django 3.0.7 on 2020-06-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200627_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='film',
            name='link_to_trailer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ссылка на трейлер'),
        ),
        migrations.AlterField(
            model_name='film',
            name='main_picture',
            field=models.ImageField(blank=True, upload_to='main_picture', verbose_name='Главная картинка'),
        ),
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название фильма'),
        ),
        migrations.AlterField(
            model_name='film',
            name='picture_gallery',
            field=models.ImageField(blank=True, height_field=190, upload_to='picture_gallery', verbose_name='Галерея картинок', width_field=1000),
        ),
        migrations.AlterField(
            model_name='film',
            name='seo_Keywords',
            field=models.CharField(blank=True, max_length=129, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='film',
            name='seo_description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='film',
            name='seo_title',
            field=models.CharField(blank=True, max_length=129, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='film',
            name='seo_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='film',
            name='type_film_2d',
            field=models.BooleanField(default=False, verbose_name='2D'),
        ),
        migrations.AlterField(
            model_name='film',
            name='type_film_3d',
            field=models.BooleanField(default=False, verbose_name='3D'),
        ),
        migrations.AlterField(
            model_name='film',
            name='type_film_imax',
            field=models.BooleanField(default=False, verbose_name='IMAX'),
        ),
    ]
