# Generated by Django 3.0.7 on 2020-06-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200627_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='picture_gallery',
            field=models.ImageField(blank=True, upload_to='picture_gallery', verbose_name='Галерея картинок'),
        ),
    ]
