# Generated by Django 3.0.7 on 2020-06-27 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200627_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='main_picture',
        ),
        migrations.CreateModel(
            name='FileFilm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_picture', models.ImageField(blank=True, upload_to='main_picture', verbose_name='Главная картинка')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Film')),
            ],
        ),
    ]
