# Generated by Django 3.0.7 on 2020-06-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20200627_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filefilm',
            name='main_picture',
        ),
        migrations.RemoveField(
            model_name='film',
            name='picture_gallery',
        ),
        migrations.AddField(
            model_name='filefilm',
            name='picture_gallery',
            field=models.ImageField(blank=True, upload_to='picture_gallery', verbose_name='Галерея картинок'),
        ),
        migrations.AddField(
            model_name='film',
            name='main_picture',
            field=models.ImageField(blank=True, upload_to='main_picture', verbose_name='Главная картинка'),
        ),
    ]
