# Generated by Django 3.0.7 on 2020-06-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kinouser',
            name='age',
            field=models.PositiveSmallIntegerField(default='30', verbose_name='Возраст'),
        ),
    ]
